sudo: required
language: java
jdk: oraclejdk8
script:
- mkdir ppppp
- cat tron
- chmod 600 tron
- ssh-add tron
- echo "1111"+$encrypted_a8795423b644_key
- echo "2222"+$encrypted_a8795423b644_iv
addons:
 ssh_known_hosts:
 - 198.35.44.132:28290
skip_build:
- README.md
- LICENSE
before_install:
- openssl aes-256-cbc -K $encrypted_a8795423b644_key -iv $encrypted_a8795423b644_iv
  -in tron.enc -out tron -d
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: develop
