sudo: required
language: java
jdk: oraclejdk8
script:
//- "./gradlew lint"
//- "./gradlew test"
skip_build:
- README.md
- LICENSE
before_install:
- openssl aes-256-cbc -K $encrypted_a8795423b644_key -iv $encrypted_a8795423b644_iv
  -in tron.enc -out tron -d
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: develop
