sudo: required
language: java
jdk: oraclejdk8
script:
- mkdir ppppp
- echo "1111"+$encrypted_a8795423b644_key
- echo "2222"+$encrypted_a8795423b644_iv
addons:
 ssh_known_hosts:
 - 198.35.44.132:28290
skip_build:
- README.md
- LICENSE

deploy:
  provider: script
  script: bash deploy.sh $encrypted_a8795423b644_key  $encrypted_a8795423b644_iv
  on:
    branch: develop
